import Card from '@components/Card';
import List from '@components/List';

export default {
  title: 'Component/List',
  component: List,
  argTypes: {
    limit: {
      defaultValue: 5,
      control: { type: 'number' },
    },
    offset: {
      defaultValue: 0,
      control: { type: 'number' },
    },
    gap: {
      defaultValue: 0,
      control: { type: 'range', min: 0, max: 50 },
    },
  },
};

const items = [
  {
    role: 'Regular',
    emailVerified: false,
    banned: false,
    isOnline: false,
    posts: [],
    likes: [],
    comments: [],
    followers: [],
    following: [],
    notifications: [],
    messages: [],
    _id: '99',
    fullName: 'temp6',
    email: 'temp',
    createdAt: '2022-06-08T06:05:55.949Z',
    updatedAt: '2022-06-08T06:05:55.949Z',
    __v: 0,
  },
  {
    role: 'Regular',
    emailVerified: false,
    banned: false,
    isOnline: false,
    posts: [],
    likes: [],
    comments: [],
    followers: [],
    following: [],
    notifications: [],
    messages: [],
    _id: '98',
    fullName: 'temp5',
    email: 'temp',
    createdAt: '2022-06-08T06:05:55.949Z',
    updatedAt: '2022-06-08T06:05:55.949Z',
    __v: 0,
  },
  {
    role: 'Regular',
    emailVerified: false,
    banned: false,
    isOnline: false,
    posts: [],
    likes: [],
    comments: [],
    followers: [],
    following: [],
    notifications: [],
    messages: [],
    _id: '97',
    fullName: 'temp4',
    email: 'temp',
    createdAt: '2022-06-08T06:05:55.949Z',
    updatedAt: '2022-06-08T06:05:55.949Z',
    __v: 0,
  },
  {
    role: 'Regular',
    emailVerified: false,
    banned: false,
    isOnline: false,
    posts: [],
    likes: [],
    comments: [],
    followers: [],
    following: [],
    notifications: [],
    messages: [],
    _id: '96',
    fullName: 'temp3',
    email: 'temp',
    createdAt: '2022-06-08T06:05:55.949Z',
    updatedAt: '2022-06-08T06:05:55.949Z',
    __v: 0,
  },
  {
    role: 'Regular',
    emailVerified: false,
    banned: false,
    isOnline: false,
    posts: [],
    likes: [],
    comments: [],
    followers: [],
    following: [],
    notifications: [],
    messages: [],
    _id: '95',
    fullName: 'temp2',
    email: 'temp',
    createdAt: '2022-06-08T06:05:55.949Z',
    updatedAt: '2022-06-08T06:05:55.949Z',
    __v: 0,
  },
  {
    role: 'Regular',
    emailVerified: false,
    banned: false,
    isOnline: false,
    posts: [],
    likes: [],
    comments: [],
    followers: [],
    following: [],
    notifications: [],
    messages: [],
    _id: '94ds',
    fullName: 'temp1',
    email: 'temp',
    createdAt: '2022-06-08T06:05:55.949Z',
    updatedAt: '2022-06-08T06:05:55.949Z',
    __v: 0,
  },
];

export function Default(args) {
  return <List items={items} keyName="_id" frame={<Card.User />} {...args} />;
}
